[package]
name = "ukiyo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "ukiyo"
crate-type = ["cdylib"]

[dependencies]
colored = "2.0.0"
pest = "2.6.0"
pyo3 = "0.18.3"
